## EDA clean AC tpye 
- Just get the name without the plane type

In [9]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import geopy 
%matplotlib inline

In [10]:
df = pd.read_json("data/silver/1920_2024_geopy.json")
df.Ground = df.Ground.astype("Int64") 
df.Date = pd.to_datetime(df.Date)

In [16]:
df

,Decade,Date,Time,Location,Operator,Flight_Num,Route,Ac_Type,Registration,Cn_Ln,Aboard,Fatalities,Ground,Summary,Country_location
0,1950,1969-12-31 23:51:03.888000,2139,"Belfast, Northern Ireland",British European Airways,None,Northolt - Belfast,Vickers Viking 610-1B,G-AJDL,262,"{'total': 35, 'passengers': 31, 'crew': 4}","{'total': 27, 'passengers': 24, 'crew': 3}",0,Crashed into approach lights while attempting ...,"Belfast, County Antrim, Northern Ireland / Tua..."
1,1950,1969-12-31 23:51:04.060800,2055,"Issaquah, Washington",Flying Tiger Line,841,Seattle - Cheyenne - Fort Jackson,Douglas C-54B-10-DO,N86574,18350,"{'total': 7, 'passengers': 3, 'crew': 4}","{'total': 7, 'passengers': 3, 'crew': 4}",0,The plane struck a tree on a mountain ridge at...,"Issaquah, King County, Washington, United States"
2,1950,1969-12-31 23:51:04.060800,0412,"Fish Haven, Idaho",Associated Air Transport,1-6-6A,Boeing Field - Cheyenne,Curtiss C-46,N1648M,22395,"{'total': 40, 'passengers': 37, 'crew': 3}","{'total': 40, 'passengers': 37, 'crew': 3}",0,The plane crashed into mountains while en rout...,"Fish Haven, Bear Lake County, Idaho, 83287, Un..."
3,1950,1969-12-31 23:51:04.752000,0448,"25 nm off Agrigento, Italy",Military -Royal Air Force,-,None,Vickers Valetta Mk1 / Avero Lancaster,VX562 / TX270,None,"{'total': 26, 'passengers': 16, 'crew': 10}","{'total': 26, 'passengers': 16, 'crew': 10}",0,Both aircraft crashed after a midair collision...,Italia
4,1950,1969-12-31 23:51:05.702400,1144,"Sinnai, Sardinia, Italy",Linee Aeree Italiane,None,Cagliari - Rome,Douglas DC-3,I-LAIL,4308,"{'total': 19, 'passengers': 15, 'crew': 4}","{'total': 19, 'passengers': 15, 'crew': 4}",0,Crashed 10 miles east of Cagliari in the Sinna...,"Sìnnia/Sinnai, Casteddu/Cagliari, Sardigna/Sar..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5032,1970,1970-01-01 00:03:39.628800,1940,"Ust-Kut, Russia",Aeroflot,None,Ust-Kut - Kirensk,Yakovlev 40,CCCP-88208,9631349,"{'total': 7, 'passengers': 4, 'crew': 3}","{'total': 7, 'passengers': 4, 'crew': 3}",0,The cargo plane crashed into trees on takeoff....,"Усть-Кут, Усть-Кутское городское поселение, Ус..."
5033,1970,1970-01-01 00:03:39.628800,21:30,"Kiev, USSR",Aeroflot,H-36,Chernivtsi - Kiev,Antonov AN-24RV,CCCP-46672,47309604,"{'total': 55, 'passengers': 50, 'crew': 5}","{'total': 48, 'passengers': 44, 'crew': 4}",0,In heavy fog the crew continued their descend...,"Служба безпеки України, Володимирська вулиця, ..."
5034,1970,1970-01-01 00:03:39.715200,1656,"Nnear Yuzhno-Sakhalinsk, Russia",Aeroflot,None,Petropavlovsk-Kamchatsky - Yuzhno-Sakhalinsk,Ilyushin IL-14M,CCCP-61752,147001247,"{'total': 8, 'passengers': 3, 'crew': 5}","{'total': 8, 'passengers': 3, 'crew': 5}",0,The survey fllight deviated from the approach ...,Россия
5035,1970,1970-01-01 00:03:40.320000,0345,"Near Bangkok, Thailand",EgyptAir,864,Cairo - Bangkok,Boeing B-707-366C,SU-AXA,20763,"{'total': 53, 'passengers': 44, 'crew': 9}","{'total': 53, 'passengers': 44, 'crew': 9}",19,The aircraft crashed into an industrial area d...,"Thailand, Banisilan, North Cotabato, Soccsksar..."
5036,1970,1970-01-01 00:03:40.838400,None,"Near Trujillo, Peru",Faucett,None,Trujillo - Tarapoto,Douglas C-54A-1-DO,OB-R-247,7462,"{'total': 19, 'passengers': 14, 'crew': 5}","{'total': 19, 'passengers': 14, 'crew': 5}",0,Struck the slope of Mt Pintado located 25 km n...,Perú